Update env.sh
Set fixed image version tag to 2.19.5 in order to fix a Java missing class issue:
java.lang.NoSuchMethodError: 'void org.apache.commons.logging.LogFactory.release(java.lang.ClassLoader)'